# Generated by Django 3.2.9 on 2021-11-21 10:09

import datetime
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=1024)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=30)),
                ('point', models.CharField(max_length=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.models.filepath)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'app_users',
            },
        ),
    ]
