# Generated by Django 3.2.9 on 2021-12-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211210_0156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFeedback',
            new_name='UserContact',
        ),
    ]
